[package]
name = "r_20240506_1318_rust_sdk"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.5"
regex = "1.10.4"
hex = "0.4.3"
futures = { version = "0.3.30", features = ["thread-pool"] }

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3


