server:
  port: 6001

spring:
  application:
    name: spring-cloud-starter-oauth2-demo
  security:
    user:
      name: root               # ???
      password: 123456   # ??
  redis:
#    database: 2
    host: localhost
    port: 6379
#    password: 1qaz@WSX
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
    timeout: 100ms

# ??????
eureka:
  instance:
    hostname: "127.0.0.1"
  client:
    #????server?????
    #    ???????? Eureka-Server ?????? true
    register-with-eureka: true
    #    ??????????????true
    fetchRegistry: true
    # ?? Eureka Client ???????????????? 30 ?
    registry-fetch-interval-seconds: 10
    serviceUrl:
      #??eureka???????? ??eureka server??????????? ?????????????????
      defaultZone: "http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}:8761/eureka/"
#      defaultZone: "http://root:123456@127.0.0.1:8761/eureka/"

management:
  endpoint:
    health:
      enabled: true