server:
  port: 10000
spring:
  application:
    name: 'mybatis-pgsql'
  datasource:
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:55433/test_db
    platform: postgresql

logging:
  level:
    root: info
    com.zaxxer.hikari: info

mybatis:
  # 加载配置文件
  mapper-locations: classpath:mapper/*/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
