server:
  port: 12000

spring:
  application:
    name: crmv2-service
  security:
    user:
      name: root               # ???
      password: 123456   # ??
  # ??????
eureka:
  instance:
    hostname: "127.0.0.1"
  client:
    #????server?????
    #    ???????? Eureka-Server ?????? true
    register-with-eureka: true
    #    ??????????????true
    fetchRegistry: true
    # ?? Eureka Client ???????????????? 30 ?
    registry-fetch-interval-seconds: 10
    serviceUrl:
      #??eureka???????? ??eureka server??????????? ?????????????????
      defaultZone: "http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}:8761/eureka/"
#      defaultZone: "http://root:123456@127.0.0.1:8761/eureka/"


