server:
  port: 10000

spring:
  application:
    name: 'mybatis-demo'
  datasource:
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/xue_gao_write_and_use?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai&allowMultiQueries=true
#  允许批量sql
#  &allowMultiQueries=true

#全部由config控制
#mybatis:
  #  config-location: ''
#  configuration:
#    map-underscore-to-camel-case: true

#logging:
#  level:
#    root: debug
